### ISSUE TITLE
Install script style improvements

### ISSUE THREAD

**Issue by ceuk** [dewhurstwill/tfvm#1]
Hey, this popped up on my feed and I just had a quick read through the setup.sh script - I don't want to clutter up your repo with a million tiny style improvements so I'll just collect a few minor comments here:

> /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/dewhurstwill/tfvm/main/setup.sh)"

Explicitly specifying the bash path is more brittle than trusting it to be in $PATH, you can also just pipe the output from curl into bash:

`curl -fsSL https://raw.githubusercontent.com/dewhurstwill/tfvm/main/setup.sh | bash`

---

From https://github.com/dewhurstwill/tfvm/blob/main/setup.sh#L60-L75

>\# Adding Alias 
string_to_check='alias tfvm'
if grep -q "$string_to_check" ~/.bashrc ; then
  echo "Already in .bashrc, Skipping..." 2>&1 >> ~/.tfvm/logs/install.log ;
else
  echo "Adding alias to bashrc" 2>&1 >> ~/.tfvm/logs/install.log ;
  echo "alias tfvm='python3 ${new_dir}/main.py'" >> ~/.bashrc ; 
fi
if grep -q "$string_to_check" ~/.bash_profile ; then
  echo "Already in .bash_profile, Skipping..." 2>&1 >> ~/.tfvm/logs/install.log ; 
else
  echo "Adding alias to bash_profile" 2>&1 >> ~/.tfvm/logs/install.log ;
  echo "alias tfvm='python3 ${new_dir}/main.py'" >> ~/.bash_profile ;
fi 

A few comments here:

1. You shouldn't need this alias, just [use a shebang](https://stackoverflow.com/questions/6908143/should-i-put-shebang-in-python-scripts-and-what-form-should-it-take) in main.py and symlink it into your $PATH
2. There's a good chance that the user might be using zsh, fish etc instead of bash in which case adding to bashrc won't be effective. `echo $SHELL` first to check. 
3. Small thing: If you are going to write something to bashrc or similar, I'd probably check first if they want you to, or just output the lines they should add, more polite :)

---

From: https://github.com/dewhurstwill/tfvm/blob/main/setup.sh#L25-L35

> \# Creating Log Location
echo Creating log location
mkdir ~/.tfvm
mkdir ~/.tfvm/logs
touch ~/.tfvm/logs/install.log
\# Creating Install Location
echo Creating install location
sudo mkdir $new_dir 2>&1 >> ~/.tfvm/logs/install.log
cd $new_dir 2>&1 >> ~/.tfvm/logs/install.log

I'm not sure you need logs for the install script TBH. Logs are great when things are happening without the user being there or when the output might be especially complex or verbose. But given that the commands you're redirecting to log files (`mkdir`, `cd`, `curl` etc) succeed silently (use `-s` for curl), you're not going to expose the user to any more noise by running them without redirection and have the added advantage that if there is something to see in stderr they will not need to work out where the log files are/cat them etc just to correct what will likely be a simple mistake

Also, if you are going to have log files for other reasons I'd suggest maybe putting them somewhere in `$XDG_CACHE_HOME` (falling back to `~/.cache`) instead. I personally find it a bit annoying when scripts dump a load of dotfiles in my home directory and it's not XDG compatible either.

---

>sudo ln -s ~/.terraform.versions/terraform /usr/local/bin/terraform 2>&1 >> ~/.tfvm/logs/install.log

Again, in the interest of keeping `~` tidy and being XDG friendly, I'd recommend sticking all your terraform versions somewhere like `$XDG_DATA_HOME/tfvm/terraform-versions` (fallback to `~/.local/share/` if $XDG_DATA_HOME isn't set. You can stick most of your files inside this tfvm folder then just symlink them where they need to be. 

---

Hope the above is useful, haven't read through the python stuff but seems like a cool idea

**Comment by dewhurstwill** [comment]
Hi @ceuk 

This is my initial build of tfvm and any feedback is greatly appreciated.
I will have a read of your comments and make changes where I see fit

Many Thanks,
Will

**Comment by dewhurstwill** [comment]
@ceuk Feel free to check out the latest changes

Thanks again,
Will
